CREATE TABLE registrations (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  event_id BIGINT NOT NULL,
  event_project_id BIGINT NOT NULL,
  id_user BIGINT NOT NULL,
  request_id BIGINT NOT NULL,
  project_token_id BIGINT NOT NULL,
  accepted_checkbox BOOLEAN NOT NULL,
  accepted_full_name VARCHAR(200) NOT NULL,
  legal_text_version VARCHAR(30) NOT NULL DEFAULT 'v1',
  accepted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status ENUM('ACTIVE','CANCELLED') NOT NULL DEFAULT 'ACTIVE',
  cancelled_at DATETIME NULL,
  cancel_reason VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_reg_event_user (event_id, id_user),
  UNIQUE KEY uk_reg_token (project_token_id),
  KEY idx_reg_event_project (event_project_id),
  CONSTRAINT fk_reg_event FOREIGN KEY (event_id) REFERENCES events(id),
  CONSTRAINT fk_reg_event_project FOREIGN KEY (event_project_id) REFERENCES event_projects(id),
  CONSTRAINT fk_reg_user FOREIGN KEY (id_user) REFERENCES users(id),
  CONSTRAINT fk_reg_request FOREIGN KEY (request_id) REFERENCES student_event_requests(id),
  CONSTRAINT fk_reg_token FOREIGN KEY (project_token_id) REFERENCES project_tokens(id)
);