INSERT INTO app_settings (k, v)
VALUES ('TOKEN_TTL_HOURS', '4')
ON DUPLICATE KEY UPDATE v = VALUES(v);

INSERT INTO app_settings (k, v)
VALUES ('ACCESS_CODE_TTL_MINUTES', '5')
ON DUPLICATE KEY UPDATE v = VALUES(v);