INSERT INTO app_settings (k, v)
VALUES ('SESSION_MAX_HOURS', '8')
ON DUPLICATE KEY UPDATE v = VALUES(v);

INSERT INTO app_settings (k, v)
VALUES ('EXPORT_MAX_ROWS_HINT', '5000')
ON DUPLICATE KEY UPDATE v = VALUES(v);