ALTER TABLE project 
MODIFY COLUMN name VARCHAR(300),
MODIFY COLUMN general_name VARCHAR(300),
MODIFY COLUMN schedule_description VARCHAR(300),
MODIFY COLUMN team_owners VARCHAR(300),
MODIFY COLUMN location VARCHAR(300),
MODIFY COLUMN audience TEXT NULL;